import type { Metadata } from "next";
import { ThemeProvider } from "./components/theme-provider";
import { Navbar } from './components/navbar';
import "./globals.css"; 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <Navbar/>
          {children}  
        </ThemeProvider>
      </body>
    </html>
  );
}
